var LIST_VIEW_ITEM_HEIGHT = 185;
var LIST_VIEW_HIGHLIGHT_SPEED = 100000;
var FILE_LIST_VIEW_ITEM_HEIGHT = 85;
var LIST_VIEW_LEFT_MARGIN = 12;
var LIST_VIEW_TOP_MARGIN = 30;
var DEFAILT_MARGIN = 5;
var FONT_NORMAL_SIZE = 25;
